steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    set -x
    
    echo "Deploying commit: $_COMMIT_SHA"
    
    # 安裝 SSH 客戶端
    apt-get update && apt-get install -y openssh-client
    
    # 準備 SSH
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    gcloud secrets versions access latest --secret=ssh-key > /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa
    
    # 添加 SSH 密鑰到 known_hosts
    ssh-keyscan -H 35.201.224.207 >> /root/.ssh/known_hosts
    
    # 使用 SSH 連接到虛擬機並執行部署腳本
    ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no lucifer_suriel@35.201.224.207 << EOF
      # 安裝 Git（如果尚未安裝）
      if ! command -v git &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y git
      fi

      # 直接在腳本中定義部署目錄
      DEPLOY_DIR="/home/lucifer_suriel/app"
      
      # 如果目錄不存在，創建它
      mkdir -p \$DEPLOY_DIR
      cd \$DEPLOY_DIR

      # 如果不是 Git 倉庫，初始化它
      if [ ! -d .git ]; then
        git init
        git remote add origin https://github.com/Gnauk841026/cloudbuild_test_control_VM.git
      fi

      # 獲取最新的變更
      git fetch origin

      # 檢出指定的 commit
      git checkout -f $_COMMIT_SHA

      # 在這裡添加您的部署命令，例如：
      # docker-compose up -d

      echo "Deployed commit $_COMMIT_SHA"
    EOF

substitutions:
  _COMMIT_SHA: ${COMMIT_SHA} # 使用內建的 COMMIT_SHA，但允許覆蓋

timeout: '1200s'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
