steps:
  # 1. 解密 SSH 密钥并保存到 /root/.ssh/id_rsa
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SSH_KEY" | base64 -d > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
    secretEnv: ['SSH_KEY']

  # 2. 使用 SSH 密钥连接到 VM 并执行命令
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no lucifer_suriel@35.201.224.207 'echo "This file was created in commit ${_COMMIT_SHA}" > /home/[USERNAME]/commit_${_COMMIT_SHA}.txt'

availableSecrets:
  secretManager:
    - versionName: projects/terraform-429505/secrets/ssh-key/versions/latest
      env: 'SSH_KEY'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
