steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    set -x
    
    # 使用提供的 SHA 或默認到最新的 commit
    TARGET_SHA=${_COMMIT_SHA:-$COMMIT_SHA}
    echo "Deploying commit: $TARGET_SHA"
    
    # 安裝 SSH 客戶端
    apt-get update && apt-get install -y openssh-client
    
    # 準備 SSH
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    gcloud secrets versions access latest --secret=ssh-key > /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa
    
    # 添加 SSH 密鑰到 known_hosts
    ssh-keyscan -H 35.201.224.207 >> /root/.ssh/known_hosts
    
    # SSH 到虛擬機執行 Git 操作
    ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no lucifer_suriel@35.201.224.207 << EOF
      set -e
      
      # 進入應用目錄
      cd /home/lucifer_suriel/app
      
      # 如果目錄不存在，進行初始克隆
      if [ ! -d .git ]; then
        git clone https://github.com/Gnauk841026/cloudbuild_test_control_VM.git .
      fi
      
      # 獲取最新的變更
      git fetch origin
      
      # 檢出指定的 commit
      git checkout $TARGET_SHA
      
      # 在這裡添加任何需要在虛擬機上執行的命令
      # 例如：重啟服務、更新配置等
      
      echo "Repository updated to commit: $TARGET_SHA"
    EOF

substitutions:
  _COMMIT_SHA: ${COMMIT_SHA} # 使用內建的 COMMIT_SHA

timeout: '1200s'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
