steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # 如果提供了 SHA，則使用它；否則獲取最新的 SHA
    if [ -n "$_MANUAL_SHA" ]; then
      echo $_MANUAL_SHA > /workspace/target_sha
    else
      git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
      cd YOUR_REPO_NAME
      git rev-parse HEAD > /workspace/target_sha
    fi
    echo "Target SHA: $(cat /workspace/target_sha)"

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    set -x

    TARGET_SHA=$(cat /workspace/target_sha)
    echo "Deploying commit: $TARGET_SHA"

    # 安裝 SSH 客戶端
    apt-get update && apt-get install -y openssh-client

    # 準備 SSH
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    gcloud secrets versions access latest --secret=ssh-key > /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa

    # 添加 SSH 密鑰到 known_hosts
    ssh-keyscan -H 35.201.224.207 >> /root/.ssh/known_hosts

    # 使用 SSH 連接到虛擬機並執行部署腳本
    ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no lucifer_suriel@35.201.224.207 << EOF
      cd /path/to/your/project
      git fetch origin
      git checkout $TARGET_SHA
      # 在這裡添加您的部署命令，例如：
      # docker-compose up -d
      echo "Deployed commit $TARGET_SHA"
    EOF

substitutions:
  _MANUAL_SHA: '' # 默認為空字符串

timeout: '1200s'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
