steps:
  # 1. 解密 SSH 密钥并保存到 /root/.ssh/id_rsa
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa

    secretEnv: ['SSH_KEY']

  # 2. 使用 SSH 密钥连接到 VM 并执行命令
  - name: 'gcr.io/cloud-builders/ssh'
    args:
      - '-i'
      - '/root/.ssh/id_rsa'
      - '-o'
      - 'StrictHostKeyChecking=no'
      - '[USERNAME]@[VM_IP]'
      - 'echo "This file was created in commit ${_COMMIT_SHA}" > /home/[USERNAME]/commit_${_COMMIT_SHA}.txt'

secrets:
- secretEnv:
    SSH_KEY: ssh-key  # 你的 Secret 名称
