steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "SSH into GCP VM and create a file"
      gcloud compute ssh [YOUR-VM-NAME] --zone=[YOUR-VM-ZONE] --command="echo 'File created by Cloud Build' > /home/[YOUR-USERNAME]/cloudbuild_test.txt"
      
# 替换 [YOUR-VM-NAME]、[YOUR-VM-ZONE] 和 [YOUR-USERNAME] 为您的实际 VM 名称、区域和用户名。

timeout: '1200s'
